name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Quay.io
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: deepakkrsharma29
          password: Password@123

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        env:
          TAG: ${{ steps.version-from-branch.outputs.version }}${{ env.TAG_SUFFIX }}
        with:
          platforms: linux/amd64,linux/ppc64le
          push: true
          tags: deepakkrsharma29/clockbox:latest
