name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v3
      
      - uses: azure/docker-login@v1
        with:
          login-server: quay.io
          username: deepakkrsharma29
          password: Password@123

      - run: |
          docker build . -t quay.io/k8sdemo:${{ github.sha }}
          docker push quay.io/k8sdemo:${{ github.sha }}
